name: Pull Request Build

on:
  push:
    branches-ignore:
      - "master"

permissions:
  contents: write

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build CLI
        run: |
          make
      - name: Run CLI tests
        env:
          STRM_TEST_USER_BILLING_ID: ${{ secrets.STRM_TEST_USER_BILLING_ID }}
          STRM_TEST_USER_EMAIL: ${{ secrets.STRM_TEST_USER_EMAIL }}
          STRM_TEST_USER_PASSWORD: ${{ secrets.STRM_TEST_USER_PASSWORD }}
          STRM_TEST_S3_USER_NAME: ${{ secrets.STRM_TEST_S3_USER_NAME }}
          STRM_TEST_S3_ACCESS_KEY_ID: ${{ secrets.STRM_TEST_S3_ACCESS_KEY_ID }}
          STRM_TEST_S3_SECRET_ACCESS_KEY: ${{ secrets.STRM_TEST_S3_SECRET_ACCESS_KEY }}
        run: |
          go test ./test -v
